from streamApp.Grammar.traitementGrammaire.StructurePhrase import StructurePhrase
from streamApp.Grammar.traitementGrammaire.Sujet import Sujet
from streamApp.Grammar.traitementGrammaire.Adverbe import Adverbe
from streamApp.Grammar.traitementGrammaire.Verbe import Verbe
from streamApp.Grammar.traitementGrammaire.MarqueurTemporel import MarqueurTemporel
from streamApp.Grammar.traitementGrammaire.MarqueursNegation import MarqueursNegation
from streamApp.Grammar.traitementGrammaire.Action import Action