from streamApp.Grammar.dictionnaireUtilisable.autresMotsLSF import PronomsLSF
from streamApp.Grammar.dictionnaireUtilisable.autresMotsLSF import Ponctuations
from streamApp.Grammar.dictionnaireUtilisable.autresMotsLSF import MarqueursTemporels
from streamApp.Grammar.dictionnaireUtilisable.autresMotsLSF import MarqueursNegation
from streamApp.Grammar.dictionnaireUtilisable.autresMotsFrançais import PronomsFR
from streamApp.Grammar.dictionnaireUtilisable.autresMotsFrançais import Prepositions
from streamApp.Grammar.dictionnaireUtilisable.autresMotsFrançais import Pluriel
from streamApp.Grammar.dictionnaireUtilisable.autresMotsFrançais import Elision